### ISSUE TITLE
dsq_sync_forum floods cron every second and destroys entire sites/servers

### ISSUE THREAD

**Issue by archon810** [disqus/disqus-wordpress#113] opened 2016-07-16 05:32 UTC
I'm going to open a proper ticket for this issue because none of the existing tickets and pull requests are descriptive enough, and what ends up happening is because of Disqus' cron jobs, entire servers go down and catch fire.

Here are some relevant urls for starters:

- https://wordpress.org/support/topic/high-server-load-and-dsq_sync_forum-problem - a topic about this on WP.org.

- The reason for why what Disqus does, which is create a cron entry every second on busy sites, is so bad (this is WP's fault): https://core.trac.wordpress.org/ticket/15148#comment:9

- https://gist.github.com/502d43fadb2afc085bd8d8ab0866a8db - a Crontrol dump of all cron jobs I took earlier today, showing that dsq_sync_forum was created over 7500 times up to that point, once every second.

- https://github.com/disqus/disqus-wordpress/blob/0f5b52af38f690342f9fd794f8af0403898547fb/disqus/disqus.php#L513 - the relevant scheduler location which basically schedules an event 5 min into the future every time cf_action = sync_comments, which seems to be every second for us (tens of thousands of people on the site at the same time).

Even if WP's flawed single db entry cron were to be fixed, the fault is still with the code above because it over-schedules so aggressively that no amount of cron-running stands any chances of catching up. 

The immediate resolution would be instead of blindly scheduling a dsq_sync_forum job, to check if one exists first.

A much better solution, though, is to schedule a 5-minutely recurring job once and forget all this sync_comments nonsense that only ends up adding millions of requests to server logs. This can easily be done using this technique: https://codex.wordpress.org/Plugin_API/Filter_Reference/cron_schedules.

Thank you in advance for quick fixes. Our and I'm sure your own servers will thank you.

**Comment by archon810** [comment] 2016-07-16 05:41
Another relevant report: https://wordpress.org/support/topic/slow-down-website-performance?replies=4.

**Comment by archon810** [comment] 2016-07-16 05:48
I see now that sync_comments exists to add a list of post_ids via AJAX to sync when the cron job runs. Alright, if that's the best way for now, that's OK. In that case, checking if there's already a scheduled dsq_sync_forum entry should do the trick.

**Comment by tail** [comment] 2016-07-16 06:59
Thanks for the detailed analysis and for the pull request.  At a glance, this looks like this has the changes I wanted in #103.  We'll test this and get this released ASAP.

**Comment by archon810** [comment] 2016-07-16 07:03
Here's something crazy to figure out. According to https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/cron.php#L0 and https://codex.wordpress.org/Function_Reference/wp_schedule_single_event, wp_schedule_single_event() actually does this: "Don't schedule a duplicate if there's already an identical event due within 10 minutes of it" by using this code:
```
$next = wp_next_scheduled($hook, $args);
if ( $next && abs( $next - $timestamp ) <= 10 * MINUTE_IN_SECONDS ) {
    return false;
}
```

However, this check doesn't seem to work 100% of the time for some reason. This fact explains why you don't see such reports every hour of every day, and why most of the time, I suppose, you won't see duplicates in cron.

Yet I was watching ours go up every time I refreshed Crontrol until the proposed (more bulletproof) PR #114.

I'll copy this comment to the Cron WP ticket for some brainstorming of what may be the cause. I suspect there's some sort of a race condition on busy sites, or some time comparison issue (maybe related to time zones).

**Comment by archon810** [comment] 2016-07-16 07:15
Here's the effect of resolving the issue with thousands of duplicate cron schedules using a forced wp_next_scheduled() check without time constraints proposed here.

See after 22:00:

- Web server (16-core 64GB RAM Linode): http://i.imgur.com/VRB0KaS.png.
- DB server (12-core 24GB RAM Linode): http://i.imgur.com/SFqXklg.png.

**Comment by archon810** [comment] 2016-07-16 08:09
Oh, another thing that may be related. 

http://i.imgur.com/1kXLh98.png

In the past day, I've started getting uncomfortable alerts about "PHP Fatal error:  Maximum execution time of 30 seconds exceeded." They happened at most every hour, sometimes several hours apart.

All of them were while in wp cron.

The crazy part is that my script timeout settings in PHP are 600 seconds, not 30. So I eventually traced this down to Disqus resetting the timeout value, except it ends up affecting the whole cron processor session and kills off cron before it has a chance to finish all the jobs and remove them from the db.

```
define('DISQUS_SYNC_TIMEOUT',       30);
set_time_limit(DISQUS_SYNC_TIMEOUT);
```

I also know that Disqus sets a lock timeout for an hour in case the sync process dies, so that it could force restart after an hour. That explains why I wasn't seeing these more often than an hour apart.

I've looked at dsq_needs_sync in post meta, and sometimes I see hundreds, if not thousands, of entries there, which means Disqus syncs comments for hundreds, if not thousands, of post IDs. As I mentioned, we have several busy sites.

If there's some sort of a slowdown in the Disqus API, the 30s timeout could suddenly become problematic. Have there been any such slowdowns lately? I'm really quite bothered by Disqus affecting cron processing for other jobs and effectively killing them, especially since WP cron has its own lock to avoid running multiple cron processors at the same time. Though I did just look it up, and WP_CRON_LOCK_TIMEOUT is set to only 60s.

Perhaps the above could have created a cascading effect of cron jobs piling up, but I can't quite come up with the logic to explain everything we've witnessed, such as multiple schedules when wp_schedule_single_event wasn't supposed to create them.

I've never gotten alerts about "PHP Fatal error:  Maximum execution time of 30 seconds exceeded" before today though - so maybe you can tell me if anything's up on your end, @tail?

**Comment by archon810** [comment] 2016-07-17 22:16
I'm continuing to see Disqus-related cron 30s timeouts. 

`select count(*) from wp_postmeta where meta_key = 'dsq_needs_sync'` returns 1638 currently. 1638 posts to sync comments for - is that something Disqus can reliably do within 30 seconds, every time @tail? 

Edit: 1666 now after 30s of waiting.

**Closed** 2016-07-21 22:13 UTC

**Comment by tail** [comment] 2016-07-21 22:20
@archon810 To clarify, it's not the `select count(*)` that's timing out, just the syncing of those 1638 posts?  It's very possible that we need to tune the timeout values.  In any case, it sounds like this is a separate issue from what you originally posted.  Do you mind creating a new issue for the sync timing out?

**Comment by tail** [comment] 2016-07-21 22:27
@archon810 Thinking about this some more, it's possible that because of the original issue, the syncs have not been occurring as frequently as they should have been and now it's trying to do a very large sync.  The way it was designed was to sync a small number of posts very frequently.  It looks like the `dsq_sync_forum` function should be clearing out "dsq_needs_sync" rows from `wp_postmeta` though (in `dsq_clear_pending_post_ids`), so I guess I'm still wondering if it's queries that are timing out before it even tries to sync.

**Comment by archon810** [comment] 2016-07-25 00:53
@tail No, select count is fast and it was just a query I used to figure out how large the queue is.

After updating 30s locally to 60s, I haven't seen a message yet, so it seems Disqus just can't sync so many posts quickly enough, even every 5 minutes, on busy sites with tens of thousands of posts.

It seems there's quite a bit of overkill as posts get flagged to be synced just because someone accesses the post page - am I understanding that right? Rather, it'd be more appropriate if they got queued when a new comment got added or something, or if the control of what posts to sync was through Disqus's servers since they'd know the exact logic of what was actually added to the Disqus DB and when. As things are now, there are lots and lots of pointless syncs going on that end up not syncing anything because there's nothing to sync.

**Comment by archon810** [comment] 2016-07-25 00:54
@tail The queries do get cleared out, eventually, so the logic works, it just doesn't account for when there could be thousands of posts as it only has 30 seconds to sync. And then it also messes up cron jobs scheduled after it in the same run.

**Comment by Crunchify** [comment] 2016-08-02 04:53
Tried fix https://github.com/disqus/disqus-wordpress/commit/ba0a89ef21e74849c7138052696b4c02c857b72c on site and it worked. Also, I would suggest to increase 5 min time to 1 hr. 

There is no advantage syncing comment every 5 min than 1 hour or 6 hrs. Comments will be added to WP DB every 1 hr instead of 5 min :)

**Comment by Crunchify** [comment] 2016-08-02 13:56
Hmm.. I take my comment back. Fix didn't work. I kept it running for ~11 hrs and saw same CPU issue again.

<img width="437" alt="screen shot 2016-08-02 at 8 55 37 am" src="https://cloud.githubusercontent.com/assets/8164601/17331085/0bd6af4e-588f-11e6-826f-149e2908a6c3.png">

**Comment by archon810** [comment] 2016-09-14 21:02
@tail Any idea when this PR is going to make it into a release tag? Right now we have a dilemma as we want to use composer and keep track of this custom change.

1. We wait for you to release it (as 2.86 or whatever) and then use wpackagist - that's the ideal situation, preferably ASAP. Because wpackagist mirrors svn, not your git repo, the changes from this PR aren't there.

2. We commit the plugin directly into our source, but then future updates would need careful merging (though hopefully, the next update will bring the only edit - this PR).

3. We figure out how to use your git repo directly with composer. Any ideas here? What I'd do then is fork your git repo, edit it locally, then pull any changes from upstream and merge them. Then we can use composer on our local fork.
